Test daily_check 15[skip actions]

diff --git a/.github/workflows/Daily_check.yml b/.github/workflows/Daily_check.yml
--- a/.github/workflows/Daily_check.yml
+++ b/.github/workflows/Daily_check.yml
@@ -43,6 +43,17 @@ jobs:
               echo "stopped|🔴 Stopped | Exit Code: $EXIT_CODE" > $OUTPUT_FILE
             fi
 
+      - name: Debug check file on remote
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          password: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            echo "Checking file existence..."
+            ls -l /home/***/container_status.txt || echo "❌ File not found!"
+
+      
       - name: Download container status result
         id: fetch
         uses: appleboy/scp-action@v0.1.7
